apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: invoice-app
type: Opaque
stringData:
  SECRET_KEY: your-secret-key-here
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  SLACK_VERIFICATION_TOKEN: ""
  SLACK_BOT_TOKEN: ""
  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  SLACK_SIGNING_SECRET: ""

