apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: invoice-app
resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - api-secret.yaml
  - api-deployment.yaml
  - ui-deployment.yaml
  - kafka-statefulset.yaml
  - kafdrop-deployment.yaml
  - ocr-worker-deployment.yaml
  - ingress.yaml

